version: "3.8"

services:
  humand-api:
    build:
      context: .
      args:
        - NODE_ENV=development
    container_name: humand-api
    env_file:
      - .env
    ports:
      - "9229:9229"
      - "8080:8080"
    volumes:
      - ./:/home/node/app:ro
    command: sh -c "npm run docker-compose-dev-start"
    networks:
      - humand
    depends_on:
      - humand-db
  humand-db:
    image: postgres:11-alpine
    container_name: humand-db
    env_file:
      - .env
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 30s
      timeout: 30s
      retries: 3
    networks:
      - humand
networks:
  humand:
